name: QI_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - affine=2.4.0=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=hef928c7_0
  - aws-c-cal=0.9.13=h2c9d079_1
  - aws-c-common=0.12.6=hb03c661_0
  - aws-c-compression=0.3.1=h8b1a151_9
  - aws-c-event-stream=0.5.7=h28f887f_1
  - aws-c-http=0.10.7=ha8fc4e3_5
  - aws-c-io=0.23.3=hdaf4b65_5
  - aws-c-mqtt=0.13.3=hc63082f_11
  - aws-c-s3=0.11.3=h06ab39a_1
  - aws-c-sdkutils=0.2.4=h8b1a151_4
  - aws-checksums=0.2.7=h8b1a151_5
  - aws-crt-cpp=0.35.4=h8824e59_0
  - aws-sdk-cpp=1.11.606=h20b40b1_10
  - azure-core-cpp=1.16.2=h206d751_0
  - azure-identity-cpp=1.13.3=hed0cdb0_1
  - azure-storage-blobs-cpp=12.16.0=hdd73cc9_1
  - azure-storage-common-cpp=12.12.0=ha7a2c86_1
  - azure-storage-files-datalake-cpp=12.14.0=h52c5a47_1
  - backports.zstd=1.3.0=py313h18e8e13_0
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py313hf159716_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cartopy=0.25.0=py313h08cd8bf_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cftime=1.6.5=py313h29aa505_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.2=pyhcf101f3_1
  - cmweather=0.3.2=pyhd8ed1ab_1
  - contourpy=1.3.3=py313hc8edb43_4
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py313h07c4f96_1
  - dask=2026.1.2=pyhcf101f3_0
  - dask-core=2026.1.2=pyhcf101f3_0
  - deprecation=2.1.0=pyh9f0ad1d_0
  - distributed=2026.1.2=pyhcf101f3_0
  - fonttools=4.61.1=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - fsspec=2026.2.0=pyhd8ed1ab_0
  - gdal=3.12.2=py313h1ee8c46_0
  - geos=3.14.1=h480dda7_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.8.1=pyhd8ed1ab_0
  - h5py=3.15.1=nompi_py313h253c126_101
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h19486de_106
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - json-c=0.18=h6688a6e_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_2
  - krb5=1.21.3=h659f571_0
  - lat_lon_parser=1.3.1=pyhd8ed1ab_1
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - lerc=4.0.0=h0aef613_1
  - libabseil=20260107.0=cxx17_h7b12aa8_0
  - libaec=1.1.5=h088129d_0
  - libarchive=3.8.5=gpl_hc2c16d8_100
  - libarrow=23.0.0=h2603568_3_cpu
  - libarrow-acero=23.0.0=h635bf11_3_cpu
  - libarrow-compute=23.0.0=h53684a4_3_cpu
  - libarrow-dataset=23.0.0=h635bf11_3_cpu
  - libarrow-substrait=23.0.0=hb4dd7c2_3_cpu
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgdal-core=3.12.2=hc2c0581_0
  - libgfortran=15.2.0=h69a702a_17
  - libgfortran5=15.2.0=h68bc16d_17
  - libgomp=15.2.0=he0feb66_17
  - libgoogle-cloud=2.39.0=h9d11ab5_1
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_1
  - libgrpc=1.78.0=h1d1128b_1
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=ha09017c_8
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libmpdec=4.0.0=hb03c661_1
  - libnetcdf=4.9.3=nompi_hbf2fc22_104
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopentelemetry-cpp=1.21.0=h9692893_2
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_2
  - libparquet=23.0.0=h7376487_3_cpu
  - libpng=1.6.55=h421ea60_0
  - libprotobuf=6.33.5=h2b00c02_0
  - libre2-11=2025.11.05=h0dc7533_1
  - librttopo=1.1.0=h46dd2a8_20
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libutf8proc=2.11.3=hfe17d71_0
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxml2-devel=2.15.1=he237659_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py313h28739b2_1
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib-base=3.10.8=py313h683a580_0
  - minizip=4.0.10=h05a5f5f_0
  - msgpack-python=1.1.2=py313h7037e92_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h5888daf_0
  - narwhals=2.16.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - netcdf4=1.7.4=nompi_py313h16051e2_102
  - nlohmann_json=3.12.0=h54a6638_1
  - numpy=2.4.2=py313hf6604e3_1
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.1=h35e630c_1
  - orc=2.2.2=hbb90d81_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py313hbfd7664_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.47=haa7fec5_0
  - pillow=12.1.0=py313h80991f8_0
  - pip=26.0.1=pyh145f28c_0
  - proj=9.7.1=he0df7b0_2
  - prometheus-cpp=1.3.0=ha5d0236_0
  - psutil=7.2.2=py313h54dd161_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=23.0.0=py313h78bf25f_0
  - pyarrow-core=23.0.0=py313h98bfbea_0_cpu
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyproj=3.7.2=py313h77f6078_2
  - pyshp=3.0.3=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.8=h2b335a9_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.13=8_cp313
  - pyyaml=6.0.3=py313h3dea7bd_1
  - qhull=2020.2=h434a139_5
  - rasterio=1.5.0=py313h2005660_0
  - re2=2025.11.05=h5301d42_1
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - s2n=1.6.2=he8a4886_1
  - scipy=1.17.0=py313h4b8bb8b_1
  - setuptools=82.0.0=pyh332efcf_0
  - shapely=2.1.2=py313had47c43_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.51.2=h04a0ce9_0
  - tblib=3.2.2=pyhcf101f3_0
  - tk=8.6.13=noxft_h366c992_103
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py313hd02dea0_0
  - tzdata=2025c=hc9c84f9_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wradlib=2.6.1=pyhd8ed1ab_0
  - xarray=2026.1.0=pyhcf101f3_0
  - xerces-c=3.3.0=hd9031aa_1
  - xmltodict=1.0.2=pyhcf101f3_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xradar=0.11.1=pyhd8ed1ab_0
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.3=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
